### ISSUE TITLE
kwargs being expected as positional arguments when handling stages in custom extractors

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#100]
**Description**
[This is an extension of #98]

When augmenting a working custom extractor [here](https://github.com/UQ4covid/uq4covid/blob/master/model_config/metawards/only_i_per_ward.py) (itself based on the `_extract_large` example in the metawards source) with stage specific switching, certain keys in the kwargs chain passed to `call_function_on_network` are expected as positional arguments.

**To Reproduce**

Additional code (first 3 lines of this function):
<pre>
def extract(stage: str, **kwargs):

	Console.print(f"stage: {stage}")
	if stage == 'initialise':
		Console.print(f"Initialise stage code here")
        
	Console.print(f"Sending I and R per ward to the output stream")
	return [output_wards_i]
</pre>

Called as:
`metawards <options> --extractor only_i_per_ward::extract`

Error:
<pre>
-------------------------------------------------------- ERROR --------------------------------------------------------
Error calling <function output_wards_i at 0x00000296E30E53A8>: <class 'TypeError'> call_function_on_network() missing 3
required positional arguments: 'infections', 'workspace', and 'population'
</pre>

Confirmed kwargs are present by adding to the output function as follows:
<pre>
def output_wards_i(nthreads: int = 1, **kwargs):
	args = ','.join(x for x in kwargs)
	Console.print(args)
	call_function_on_network(nthreads=1, func=output_wards_i_serial, call_on_overall=True, **kwargs)
</pre>

Produces:
<pre>
-------------------------------------------------------- Day 0 --------------------------------------------------------
stage: setup
Sending I and R per ward to the output stream
stage: foi
Sending I and R per ward to the output stream
state 0: scale_rate = 1.0, can_work = True
stage: infect
Sending I and R per ward to the output stream
stage: analyse
Sending I and R per ward to the output stream
network,population,infections,output_dir,workspace,rngs,profiler
network,population,infections,output_dir,workspace,rngs,profiler
network,population,infections,output_dir,workspace,rngs,profiler
network,population,infections,output_dir,workspace,rngs,profiler
Number of infections: 0
</pre>

Hence, `call_function_on_network` is not using the kwargs and is expecting positionals

**Environment (please complete the following information):**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: metawards 1.0.0+1.g3ef18524

**Comment by chryswoods** [comment]
call_function_on_network is not designed to be used for the setup stage of the calculation. It is only used for the foi, infect and analyse stages. These stages require the arguments that are missing that are highlighted, e.g. infections, as these are not ready yet when the model is being set up.

Equally, call_function_on_network is needed only when you are managing both a parallel and serial version of a function and one that handles both a Network or a Networks object. You are doing none of these in your code, so you can just call your function directly without calling it via call_function_on_network.

As I said before, I do not recommend that you use the setup stage now as the API for this stage is not stable. I strongly encourage you to setup the connection to your database via the network.params function and method I highlighted and that is in the tutorial.

I am closing this issue as the code is doing exactly as it is designed to do. Please stick to the public API and the methods described in the tutorial, as this will make your extractor easier to support and I won’t break it when I change or improve the call_function_on_network or setup stage API when I am back from holiday.

**Comment by fentonscode** [comment]
Thanks to all for input on this, I raised it as was a very easy way trap for a user to end up in after modifying the code examples / default extractors. I will let you know if our (constantly getting more complex) use case runs into any limits.
