### ISSUE TITLE
Expand the disease JSON format to include stage/state labels

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#113]
**Description**
I haven't seen this in the tutorials as yet, but for each of the disease JSON files, it would be handy to add a key which can store an array of stage/state names.

**Ideal solution**
As an example the `lurgy_home.json' file from tutorial 7 part 1

<pre>
{ "name"             : "The Lurgy",
  "version"          : "June 2nd 2020",
  "author(s)"        : "Christopher Woods",
  "contact(s)"       : "christopher.woods@bristol.ac.uk",
  "reference(s)"     : "Completely ficticious disease - no references",
  "beta"             : [0.0, 0.0, 0.5, 0.5, 0.0],
  "progress"         : [1.0, 1.0, 0.5, 0.5, 0.0],
  "too_ill_to_move"  : [0.0, 0.0, 0.5, 0.8, 1.0],
  "contrib_foi"      : [1.0, 1.0, 1.0, 1.0, 0.0]
}
</pre>

Could become:

<pre>
{ "name"             : "The Lurgy",
  "version"          : "June 2nd 2020",
  "author(s)"        : "Christopher Woods",
  "contact(s)"       : "christopher.woods@bristol.ac.uk",
  "reference(s)"     : "Completely ficticious disease - no references",
  "states"           : ["E", "I1", "I2", "I3", "R"],
  "beta"             : [0.0, 0.0, 0.5, 0.5, 0.0],
  "progress"         : [1.0, 1.0, 0.5, 0.5, 0.0],
  "too_ill_to_move"  : [0.0, 0.0, 0.5, 0.8, 1.0],
  "contrib_foi"      : [1.0, 1.0, 1.0, 1.0, 0.0]
}
</pre>

**Alternatives**
An alternative is to simply pass a set of user variables such as `.stage_label[x] = "<label>"` where x = [0, k-3], where k is the number of stages (S and holding stage are not in the disease file it appears)

**Comment by chryswoods** [comment]
Thanks @fentonscode - I agree, it would be really useful to be able to set these. At the moment they are set in a hidden way, so this should be a relatively easy fix. It would definitely help with the "go_stage" function, as well as making the outputs easier to interpret. I'll add this as an issue attached to the 1.2 milestone so that I make sure that this is included in that release.

**Comment by chryswoods** [comment]
I've added this to this feature branch issue (https://github.com/metawards/MetaWards/issues/114) so will close this issue, as discussion will move there.
