### ISSUE TITLE
Confusion over the stages array in the disease file

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#118]
**Description**
In tutorial 7 part 1, the lurgy example file contains 5 stages, yet the description text above shows 6 indices as [0, 5]. It is unclear whether the disease file `lurgy_home.json` is either [E, I1, I2, I3, R] or [*, ...], where * is the latent class of people exiting the S class.

**Comment by chryswoods** [comment]
The description at the top refers to the "lurgy4" that had been built up throughout the rest of the tutorial, which has 6 stages, as described. The "lurgy_home" and "lurgy_super" are the two new disease files that are introduced after this description, one of which has 5 stage (removed the pre-symptomatic state, as described) and the other has 6 stages (very infectious pre-symptomatic state).

For lurgy_home the states are [*, E, I2, I3, R] while for lurgy_super they are [*, E, I1, I2, I3, R]

**Comment by chryswoods** [comment]
Specifically in the tutorial directly before "lurgy_home" and "lurgy_super" there is;

"We would like to investigate how the percentage of these super-spreaders, and their mobility and infectivity affects the progression of the outbreak. To do this, we will create two demographics;

* home, which will contain a population who do not progress through the asymptomatic infectious stage, and
* super, which will contain a population of super-spreaders who do move through the asymptomatic infectious phase.

To start, we need to create disease files for the home and super demographics. Do this by creating two files, first lurgy_home.json that should contain;"

**Comment by fentonscode** [comment]
I see, it wasn't totally clear when first reading through it

For consistency of nomenclature, did we agree that * and E were to transform to E1 and E2?

**Comment by chryswoods** [comment]
Yes, in our discussions, but not in the docs. Star is called star, as the command line option "--star-as-E" means refer to star as E, while "--star-as-R" means refer to star as R, and "--disable-star" means remove the star state altogether. So, in the docs, I need to call it star as all of the tutorial is run using "--star-as-R". But feel free to call it E1 if you run using "--star-as-E"

**Comment by chryswoods** [comment]
Adding a note here from our email exchange that, yes, it is a typo when I wrote "We will move these individuals to stage 2, which is H2, in the patients demographic.". It should read "We will move these individuals to stage 2, which is H1, in the patients demographic."

**Comment by fentonscode** [comment]
If you call `--disable-star` does that change the indexing required in the movers?

**Comment by chryswoods** [comment]
No, as disable-star means that the first stage in the disease file (stage 0) is now interpreted as E, while the second stage is I1 etc. So the number of stages hasn’t changed, just how you interpret them. 

It does mean that, for the same outbreak you should delete stage 0 from the disease file, i.e. reduce lurgy4 from 6 to 5 stages, and then, because you have changed the number of stages, you would need to reindex your movers.

**Comment by chryswoods** [comment]
I'm going to close this now as I don't think there is anything that needs to change. Please feel free to re-open if I am wrong :-)
