### ISSUE TITLE
Expand valid range for named stages

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#120]
**Related**
Feature request #113

**Description**
Currently only a narrow set of disease stage labels are supported (only '*', 'E', 'I' or 'R'), anything else raises `AssertionError`. It would be extremely useful to allow custom labels.

**Comment by chryswoods** [comment]
Thanks. This is being worked on in feature_named_stages (https://github.com/metawards/MetaWards/issues/114) and is planned to be released as part of metawards 1.2. This will support completely arbitrary names, with grouping used by custom mapping (e.g. H1, H2, H2 can be grouped in H, or into I, depending on what the user wants).

Going to close as this should be discussed in the feature issue.
