### ISSUE TITLE
 pdf Document

### ISSUE THREAD

**Issue by wenchaohee** [metawards/MetaWards#186]
Hi, I was wondering is there any tutorial with the pdf version, which would be easier to read. Thanks for your time.

**Comment by chryswoods** [comment]
Sorry - the tutorial has only been generated as html.

**Comment by chryswoods** [comment]
I am having a go to see if I can get sphinx to generate a nice PDF. I will let you know how I get on

**Comment by chryswoods** [comment]
Ok, I have had a go at getting the PDF to compile. You can [download it here](https://drive.google.com/file/d/1ESY1eLzae3AZJSRtwfXrfcoHmOwH5QEb/view?usp=sharing). 

The tutorial is in Chapter 7, on page 57. I had a bit of trouble getting latex to handle some of the unicode in the example output, so some of the tables look a bit weird. Otherwise, I think it mostly ok.

**Comment by mauimoana** [comment]
Wow, I get the PDF. It is awesome. Thanks for your help. 
Well, I also come into a installation problem. Though I can install the metaward package in Linux system but I failed in Windows system. I am not sure it's my problem or the package. Thanks for your time.
![image](https://user-images.githubusercontent.com/77086328/159232884-5b322e08-01fd-4e11-9f69-18e8e5af1745.png)

**Comment by chryswoods** [comment]
No problem :-)

From the error, it looks like lazy-import is not installing correctly. There is an undecodable bit of unicode text in one of the input files or source files of lazy-import (this is the illegal multibyte sequence error). Pip fails to install lazy-import, which then means that it can't go on and install metawards.

Could you try and install lazy-import manually, i.e. `pip install lazy_import==0.2.2`, or even try to install using conda? If this doesn't work, download the lazy-import source code directly and use `python setup.py install` in the lazy-import source directory to install it.

I believe that metawards should install ok once lazy-import is in place. I do not know why lazy-import is no longer working. It could be either that it got corrupted when it was downloaded, or that they have made an update that breaks installation on windows.

**Comment by chryswoods** [comment]
(sorry - the command should be `pip install lazy_import==0.2.2`)

**Comment by mauimoana** [comment]
Thank you for your detailed help. I have tried every method you mentioned above but failed in installing the package. Well, since I can install the metaward in Linux, I can use the package on that platform. So, It doesn't bother me much. 
Thank you for your help. Best wishes.

**Comment by chryswoods** [comment]
Ok - good to hear that it is working on Linux. Do get back in touch if there is anything else you need :-)
