### ISSUE TITLE
Pip install fails due to missing dependencies

### ISSUE THREAD

**Issue by lohedges** [metawards/MetaWards#2]
I am unable to install the package using pip:

```sh
(metawards) ~/C/MetaWards ❯❯❯ pip install metawards                                                                                                                            devel
Collecting metawards
  Downloading metawards-0.2.0.tar.gz (1.4 MB)
     |████████████████████████████████| 1.4 MB 525 kB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/lester/.conda/envs/metawards/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hh/jnrvnpbx0dv1m6m0jy6p15vm0000gs/T/pip-install-zax6oyvy/metawards/setup.py'"'"'; __file__='"'"'/private/var/folders/hh/jnrvnpbx0dv1m6m0jy6p15vm0000gs/T/pip-install-zax6oyvy/metawards/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hh/jnrvnpbx0dv1m6m0jy6p15vm0000gs/T/pip-install-zax6oyvy/metawards/pip-egg-info
         cwd: /private/var/folders/hh/jnrvnpbx0dv1m6m0jy6p15vm0000gs/T/pip-install-zax6oyvy/metawards/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hh/jnrvnpbx0dv1m6m0jy6p15vm0000gs/T/pip-install-zax6oyvy/metawards/setup.py", line 7, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I assume that this is because nothing is set in the `install_requires` option within `setup.py`. At present it appears to be set to the contents of an empty `requirements.txt` file. I assume that we need to add `cython`, `pygsl` (and possibly `numpy`) to this file.

**Comment by chryswoods** [comment]
It will work if libgsl is installed (although it has to be the same version as on my machine, which is an annoying limitation I found after building and uploading the package).

I removed pygsl and have now bundled the Numpy rng into the package. Once fully tested will build a new package and upload by end of Sunday. Current test in extract_gsl branch is good.

Result of this will be the need for Cython to build, but no dependencies for running.

**Comment by chryswoods** [comment]
This error is because of Cython (my mind last night was still on gsl...!). I need to make changes to setup.py so that when I make the pip package it bundles the Cython generated C files into the package. I don’t want the Cython files in the repo though as they are derived files.

Thus I should put Cython into the dev requirements file, and fix the pip packaging...

Also a Sunday job (am resting today)

**Comment by chryswoods** [comment]
I've made a new pip package (0.3.1) which (I believe) includes the C files, and also specifies cython as a dependency in case not, so that they can be generated.
