### ISSUE TITLE
Unit test failure within test_fingerprints.py

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#49]
**Description**

Unit tests on fingerprinting fail when trying both the general testing suite and the fingerprint test with the -v option. commands. The console output is attached (not browser friendly!).

**Reproduction**
From Windows PowerShell / cmd prompt inside MetaWards directory run:
"pytest tests"
or 
"pytest -v tests/test_fingerprints.py"

**Screenshots**
Console output attached
![consoleout](https://user-images.githubusercontent.com/8965253/81163001-fc079880-8f85-11ea-905f-2f06d4567000.png)

**Environment**
 - OS: Windows 10
 - Python: 3.7.4
 - Version:  MetaWards 0.10.0

**Comment by chryswoods** [comment]
Thanks - could you run the below code and let me know what the output is? (also, yes, -vv is correct - it means "really verbose" ;-)).

```python
from metawards import VariableSet 
v = [0, 1, 2, 3, 4]
fingerprint = VariableSet.create_fingerprint(v)
print(fingerprint)
print(VariableSet.extract_values(fingerprint))
```

Either copy the above into a file and run that, or type it into ipython or a jupyter notebook. On ipython I get;

```python
In [1]: from metawards import VariableSet                                                 
In [2]: v = [0, 1, 2, 3, 4]                                                               
In [3]: fingerprint = VariableSet.create_fingerprint(v)                                   
In [4]: print(fingerprint)                                                                
0:1:2:3:4
In [5]: print(VariableSet.extract_values(fingerprint))                                    
([0.0, 1.0, 2.0, 3.0, 4.0], None) 
```

**Comment by fentonscode** [comment]
Output from the JetBrains Python terminal (same output on 'raw' terminal from the command line)

<pre>
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
In [1]: from metawards import VariableSet
   ...: v = [0, 1, 2, 3, 4]
   ...: fingerprint = VariableSet.create_fingerprint(v)
   ...: print(fingerprint)
   ...: print(VariableSet.extract_values(fingerprint))
0:1:2:3:4
([], None)
</pre>

However, after reinstalling MetaWards from a fresh clone and this disappeared. I can't see anything obvious in the extract_values() code either.

**Comment by chryswoods** [comment]
That is very strange. I thought you may have an older metawards python library being loaded accidentally, which is why I wanted to see the fingerprint that was generated (we changed the format between 0.9.0 and 0.10.0). The fingerprint was the new format though, so I don’t understand how it generated the new format but couldn’t parse it.

As I said very strange, but good that a fresh install has fixed it. Feel free to close this issue now if you are happy this is resolved. Thanks for reporting the error and for helping debug it. :-)
