### ISSUE TITLE
Finger-printing is creating invalid folder names for windows

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#56]
**Description**
Using the separator ":" and token "@" results in invalid folder names when trying to create the output folders for runs on windows (NOTE: '@' is technically fine, but not recommended).

Sample error message:

<pre>  File "python\python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
OSError: [Errno 22] The filename, directory name, or volume label syntax is incorrect: 'output\\0_5:0_5:0_5:0_5:0_5@001'</pre>

**To Reproduce**
Run with any input file that uses adjusted variables (as per tutorial 2). E.g.: <pre>metawards -d lurgy2 -a ExtraSeedsLondon.dat --input lurgyparams.csv</pre>

**Environment**
 - OS: Windows 10 x64
 - Python: 3.7.4 + All optional and development requirements
 - Version metawards 0.10.0

**Additional context**
See bullet point 6 under naming conventions [here](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)

**Comment by chryswoods** [comment]
Thanks - I’ll come up with a different separator. Challenging as there’s a long list that I can’t use due to Linux and OS X character restrictions too...

The code that creates and decodes fingerprints is here

https://github.com/metawards/MetaWards/blob/1616684d2ec9dff459f8a43b32cec752d73efe8e/src/metawards/_variableset.py#L632

Feel free to choose a separator temporarily that works for you on windows so that you can keep working through the tutorial. I’ll look for alternatives first thing tomorrow.

**Comment by fentonscode** [comment]
I used 'v' in a previous clone to practice, but didn't want to commit with all the earlier changes. Would that break any formatting styles for your end?

**Comment by chryswoods** [comment]
Yes - I feel kind of silly that I forgot I could use normal letters! ;-)

Yes, I like using “v” as the separator for variables and “x” to replace the “@“ (as repeat x01 looks meaningful). Choosing o as it looks small and simple.

Fingerprints would be 

1_0v0_5x01
0_9v1_0x02

etc

**Comment by chryswoods** [comment]
I've applied this fix in the linked pull request - thanks for raising the issue and for pointing out the obvious fix :-). I've been using this fingerprinting scheme for a few days now and it looks so much easier on the eye, e.g.

```
:-> ls output/
0_2v0_1x001  0_2v0_3x003  0_3v0_1x003  0_3v0_5x001  0_4v0_3x002  0_5v0_1x003  0_5v0_5x001
0_2v0_1x002  0_2v0_3x004  0_3v0_2x001  0_3v0_5x002  0_4v0_3x003  0_5v0_2x001  0_5v0_5x002
0_2v0_1x003  0_2v0_4x001  0_3v0_2x002  0_3v0_5x003  0_4v0_4x001  0_5v0_2x002  0_5v0_5x003
0_2v0_1x004  0_2v0_4x002  0_3v0_2x003  0_4v0_1x001  0_4v0_4x002  0_5v0_2x003  0_5v0_5x008
0_2v0_2x001  0_2v0_4x003  0_3v0_3x001  0_4v0_1x002  0_4v0_4x003  0_5v0_3x001
0_2v0_2x002  0_2v0_5x001  0_3v0_3x002  0_4v0_1x003  0_4v0_5x001  0_5v0_3x002
0_2v0_2x003  0_2v0_5x002  0_3v0_3x003  0_4v0_2x001  0_4v0_5x002  0_5v0_3x003
0_2v0_2x004  0_2v0_5x003  0_3v0_4x001  0_4v0_2x002  0_4v0_5x003  0_5v0_4x001
0_2v0_3x001  0_3v0_1x001  0_3v0_4x002  0_4v0_2x003  0_5v0_1x001  0_5v0_4x002
0_2v0_3x002  0_3v0_1x002  0_3v0_4x003  0_4v0_3x001  0_5v0_1x002  0_5v0_4x003
```

This issue will automatically close once I accept the pull request.

**Comment by chryswoods** [comment]
Just to say that this is all now in the devel branch. I've had to change the decimal point separator to 'i" so that the animate part of metawards-plot was easier to write (too many overloaded meanings of underscore). Chosen 'i' as it least there is a dot at the top.

```
0i2v0i1x001     0i2v0i5x002     0i3v0i4x003     0i4v0i3x004     0i5v0i2x005
0i2v0i1x002     0i2v0i5x003     0i3v0i4x004     0i4v0i3x005     0i5v0i2x006
0i2v0i1x003     0i2v0i5x004     0i3v0i4x005     0i4v0i3x006     0i5v0i2x007
0i2v0i1x004     0i2v0i5x005     0i3v0i4x006     0i4v0i3x007     0i5v0i2x008
0i2v0i1x005     0i2v0i5x006     0i3v0i4x007     0i4v0i3x008     0i5v0i3x001
0i2v0i1x006     0i2v0i5x007     0i3v0i4x008     0i4v0i4x001     0i5v0i3x002
0i2v0i1x007     0i2v0i5x008     0i3v0i5x001     0i4v0i4x002     0i5v0i3x003
0i2v0i1x008     0i3v0i1x001     0i3v0i5x002     0i4v0i4x003     0i5v0i3x004
0i2v0i2x001     0i3v0i1x002     0i3v0i5x003     0i4v0i4x004     0i5v0i3x005
0i2v0i2x002     0i3v0i1x003     0i3v0i5x004     0i4v0i4x005     0i5v0i3x006
0i2v0i2x003     0i3v0i1x004     0i3v0i5x005     0i4v0i4x006     0i5v0i3x007
0i2v0i2x004     0i3v0i1x005     0i3v0i5x006     0i4v0i4x007     0i5v0i3x008
0i2v0i2x005     0i3v0i1x006     0i3v0i5x007     0i4v0i4x008     0i5v0i4x001
0i2v0i2x006     0i3v0i1x007     0i3v0i5x008     0i4v0i5x001     0i5v0i4x002
0i2v0i2x007     0i3v0i1x008     0i4v0i1x001     0i4v0i5x002     0i5v0i4x003
0i2v0i2x008     0i3v0i2x001     0i4v0i1x002     0i4v0i5x003     0i5v0i4x004
0i2v0i3x001     0i3v0i2x002     0i4v0i1x003     0i4v0i5x004     0i5v0i4x005
0i2v0i3x002     0i3v0i2x003     0i4v0i1x004     0i4v0i5x005     0i5v0i4x006
0i2v0i3x003     0i3v0i2x004     0i4v0i1x005     0i4v0i5x006     0i5v0i4x007
0i2v0i3x004     0i3v0i2x005     0i4v0i1x006     0i4v0i5x007     0i5v0i4x008
0i2v0i3x005     0i3v0i2x006     0i4v0i1x007     0i4v0i5x008     0i5v0i5x001
0i2v0i3x006     0i3v0i2x007     0i4v0i1x008     0i5v0i1x001     0i5v0i5x002
0i2v0i3x007     0i3v0i2x008     0i4v0i2x001     0i5v0i1x002     0i5v0i5x003
0i2v0i3x008     0i3v0i3x001     0i4v0i2x002     0i5v0i1x003     0i5v0i5x004
0i2v0i4x001     0i3v0i3x002     0i4v0i2x003     0i5v0i1x004     0i5v0i5x005
0i2v0i4x002     0i3v0i3x003     0i4v0i2x004     0i5v0i1x005     0i5v0i5x006
0i2v0i4x003     0i3v0i3x004     0i4v0i2x005     0i5v0i1x006     0i5v0i5x007
0i2v0i4x004     0i3v0i3x005     0i4v0i2x006     0i5v0i1x007     0i5v0i5x008
0i2v0i4x005     0i3v0i3x006     0i4v0i2x007     0i5v0i1x008     results.csv.bz2
0i2v0i4x006     0i3v0i3x007     0i4v0i2x008     0i5v0i2x001
0i2v0i4x007     0i3v0i3x008     0i4v0i3x001     0i5v0i2x002
0i2v0i4x008     0i3v0i4x001     0i4v0i3x002     0i5v0i2x003
0i2v0i5x001     0i3v0i4x002     0i4v0i3x003     0i5v0i2x004
```

**Comment by fentonscode** [comment]
Perhaps a database or other binary output as a future replacement?
