### ISSUE TITLE
[DOCS] - Mention that metawards-plot requires MatplotLib

### ISSUE THREAD

**Issue by lohedges** [metawards/MetaWards#64]
In the [Plotting outputs](https://metawards.org/tutorial/part01/03_plotting.html) section in might be worth mentioning that `metawards-plot` requires `MatplotLib` as a dependency. It's pretty obvious from the error message, but it might be nice to mention this to the reader, like you do with `Pandas` in the previous section. Perhaps `MatplotLib` could be added as an optional dependency using the [extras_require](https://setuptools.readthedocs.io/en/latest/setuptools.html#id15) section of `setup.py`.

**Comment by chryswoods** [comment]
I'd ideally like to get metawards-plot to ask the user if they want to install the optional dependencies at use time, e.g. "do you want to install these now?" and then do that. I don't want these optional dependencies going into setup.py as I don't want to risk having the install of the main code being derailed by issues with optional deps (there are so many weird bugs when installing matplotlib etc that I don't want users to have to deal with when first installing and trying metawards)

**Comment by lohedges** [comment]
Good point. I think a warning message with would be a good idea. That said, I don't think `extra_requires` would affect the vanilla MetaWards install, only the user could do something like `make plot`, or `python setup.py plot` to pull in the additional deps for `metawards-plot`. Not sure how this would work if they were installing via PyPi rather than source though.

**Comment by chryswoods** [comment]
Thanks for fixing the jpg issue. I've been learning to keep setup.py as simple as possible and try not to have dependencies, as it can be a nightmare. One thought I had was to add this as an argument to metawards-plot, e.g.

```
metawards-plot --install-deps
```

would install all of the optional dependencies, trying first to install properly, and then if that fails, installing as --user. It could even do;

```
metawards-plot --install-deps --dry-run
```

to show what it is trying to install, so that a sysadmin could install them in a different way if needed. The code should "try import" and only install if it is missing. What do you think?

**Comment by lohedges** [comment]
Yes, that sounds like a good idea, especially having a dry-run to show what would be installed. This would help avoid problems if the user happens to have a weird Python set up.

I definitely agree about keeping setup.py nice and simple. It's difficult enough dealing with your own issues, let alone managing an ever changing set of problems as your dependencies mutate. (If only BioSimSpace were a pure-python package with no dependencies!)

**Comment by chryswoods** [comment]
Could you take a look at doing this? The apps are all in the src/metawards/app directory (plot.py is metawards-plot)

**Comment by lohedges** [comment]
Yes, I'd be happy to take a look. Just to check: the packages needed for full plotting functionality are `pandas`, `matplotlib`, and `pillow`?

**Comment by chryswoods** [comment]
Yes - that's almost fully correct. pandas for data loading, matplotlib for plotting, and pillow for drawing figures and creating gifs. There is also pygifsicle that is used for optimising the gifs, but this depends on an external C program being compiled and installed (gifsicle). It is well worth it as it reduces gif size by about 10x-100x

**Comment by lohedges** [comment]
Ah yes, good old gifsicle. I had that installed already so didn't experience any problems :-)

**Comment by chryswoods** [comment]
It is very easy to compile and install, so I'd even consider having the "--install" download, compile and install gifsicle, or at least make suggestions on how to do that.

**Comment by chryswoods** [comment]
I think you may need to install pygifsicle though as the gif you uploaded (tutorial_2_3.gif was not optimised - was 2.4 MB, but when optimised it is 407 KB). The code skips the optimisation step if pygifsicle is not available (see https://github.com/metawards/MetaWards/blob/c89c114313651c3096525b2abfb6467d60ac050a/src/metawards/analysis/_animate_plots.py#L172)

**Comment by lohedges** [comment]
Ah, sorry about that. I didn't check the file size before committing. I'll make sure to optmise the gifs for any other updates to the docs.

**Comment by chryswoods** [comment]
It's not a problem. The deduplicate script will replace this for all versions of the website once we make a release. It did surprise me how poorly PIL wrote the gifs though - for some the filesize was dozens of MB!

**Comment by chryswoods** [comment]
Closing as I've now made this change in commit 70bf478aa3feb749cbee7b832e669499b8113d45. This includes adding "metawards-install" to install dependencies and check for the presence of gifsicle.
