### ISSUE TITLE
[DOCS] - Update to new fingerprint format

### ISSUE THREAD

**Issue by lohedges** [metawards/MetaWards#67]
This is a pretty minor issue, but the code snippets on [this](https://metawards.org/tutorial/part02/03_analysis.html) page, i.e. the pandas output, should probably be updated to reflect the new fingerprinting format. No need to do this until you settle on a final format.

For example, I currently see something like this:

```python
>>> df.groupby("fingerprint")[["day", "E","I", "IW", "R"]].max()
             day        E         I    IW         R
fingerprint
0i3v0i0      223  1867602   9124999  8588  48107545
0i3v0i25     213  1806030   8849753  8588  48080295
0i3v0i5      203  1925482   9373635  8588  48050991
0i4v0i0      191  1926941   9441320  8588  49044169
0i4v0i25     209  2013614   9815751  8588  49007451
0i4v0i5      196  2049927   9994566  8588  48979256
0i5v0i0      177  2108287  10278260  8588  49861436
0i5v0i25     180  2093600  10215078  8588  49814876
0i5v0i5      173  2070325  10128212  8588  49779655
```

whereas the tutorial example has:

```python
>>> df.groupby("fingerprint")[["day", "E","I", "IW", "R"]].max()
              day        E         I    IW         R
 fingerprint
 3_0          204  1767303   8665472  8588  48105748
 3_25         205  1908160   9296754  8588  48076343
 3_5          215  1844377   9024418  8588  48036902
 4_0          192  1947245   9532789  8588  49042717
 4_25         210  1965166   9614400  8588  49009034
 4_5          200  2095342  10179621  8588  48975523
 5_0          175  2207896  10714530  8588  49857969
 5_25         183  2120481  10326984  8588  49821966
 5_5          176  2117730  10330952  8588  49777968
```

**Comment by chryswoods** [comment]
Please feel free to update any outputs to match the newest code version. The docs are versioned, so it would be good if the snippets for the current version match the seen outputs. One day (i.e. distant future) I'd like to have all of the examples in the tutorial run automatically in a separate repo whenever we build a new release. They are a fantastic tool for testing, and preparing the tutorial has unearthed more bugs than just simple unit tests.

**Comment by lohedges** [comment]
That's a good idea. I totally agree about tutorial material being a great way to iron out issues with the usability of the code. The BioSimSpace workshops were really helpful in this regard too.

**Comment by lohedges** [comment]
I'm currently working through this [here](https://github.com/metawards/MetaWards/pull/68).

**Comment by chryswoods** [comment]
Closing as I've merged in your pull request
