### ISSUE TITLE
Ability to supply an array of repeats to MetaWards

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#71]
**Description**
In our analysis of the model we would like to have the availability to run some design points a different number of times to others. At the moment we can set --repeats to a single value, but this will not be sufficient.

**Alternatives**
A clear alternative is to separate an input design variables file into multiple designs and call MetaWards for each one. However, this requires a significant amount of processing both on the input and output stages. Another alternative is to expand the design file and run without repeats, however I have found that running without repeats, or repeats less than cores / 2 is slower than `--repeats x` where `cores / 2 < x < cores` - which will often mean some very slow runs.

**Comment by fentonscode** [comment]
Also, it is unclear from the documentation whether the second alternative will work as it will try to overwrite variables with the same fingerprint

**Comment by chryswoods** [comment]
That sounds like a good idea. I can make it so that if you pass in more than one number to "--repeats" that it treats that like a list, and VariableSet[i] is repeated repeats[i] times. I'll see if I can do that by Monday

**Comment by fentonscode** [comment]
Ideal usage be to have a design file like the following

<pre>
beta[2],beta[3],repeats
0.0,1.0,1
1.0,0.5,6
...
</pre>

Where a column can control the repeats. Would that parse into VariableSet[]?

**Comment by chryswoods** [comment]
Yes, that is also a great idea. I will implement both methods, and where both repeats values are set they will multiply (e.g. --repeats 2 for your design file would do the first row twice, and the second row 12 times).

**Comment by chryswoods** [comment]
Working on this now in [fix-issue-71](https://github.com/metawards/MetaWards/tree/fix-issue-71). This issue will close automatically once I've pulled this fix into devel. It will be part of the 0.12.0 release.

**Comment by chryswoods** [comment]
I've now added "repeats" to the file, as you asked, and also allowed this to be specified on the command line, e.g. --repeats 2 4 6

This is now testing. Once the tests pass this will be merged into the latest version of devel, which will close this issue.
