### ISSUE TITLE
Iterators documentation needs slight alteration to code samples

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#73]
**Documentation / tutorial problem**
Similar to the previous discussion on extractors, having imports outside of the iterator functions ends up building the default iterator instead. Moving them internal to the iterator clears the issue, as it did with the extractors

**Location**
Example: https://metawards.org/tutorial/part03/02_weekend.html#changing-iterators-with-time

**Environment (if applicable, please complete the following information):**
 - OS: Windows 10
 - Python: 3.7.4
 - Version: MetaWards latest (unsure what version it really is now) - as of a few minutes ago

**Comment by chryswoods** [comment]
The version of metawards is printed at top of the output file, e.g.

            ************************
            metawards version 0.11.2
            ************************

Version 0.11.2 has the fix that matches the last function in the file, so it behaves more as you expect (and the docs imply). You were right that it is more natural and normal to put the import at the top of the file.

If it is not working for 0.11.2 then let me know as that’s a code bug now rather than a doc bug. If that is the case then post the iterator you’ve written and I’ll debug what went wrong.

**Comment by fentonscode** [comment]
MetaWards says:

<pre>metawards version 0.10.0+155.g8e43017</pre>

Should I still be pulling from devel - or is it now master? This is from `git pull upstream devel` an hour ago, where the upstream remote is this repo

**Comment by chryswoods** [comment]
Thanks - I am not sure why, but your pull from devel is not up to date. I follow a "feature" => "devel" => "master" repository structure, as described here - https://metawards.org/versions/devel/packaging.html.

The two last pulls from a feature branch into devel were late last Friday (https://github.com/metawards/MetaWards/pull/72 - created version 0.11.2+37.g01d89daf, metawards reports "last modified: 2020-05-15T19:22:06+0100", get it via "git checkout 01d89da") and last Wednesday (https://github.com/metawards/MetaWards/pull/70 - created version 0.11.2+14.g64fa0887, metawards reports "last modified: 2020-05-12T18:24:42+0100", get it via "git checkout 64fa088").

Both of these have the fixed behaviour of matching the last iterator in a file, and I've double checked and the example in the tutorial works.

You version number of 0.10.0+XXXX indicates that somehow your devel clone has got stuck on a version that is before the 0.11.0 release. Could you double-check that you are pulling the latest version of devel? The merge on Friday made a major change to the console output, so if you are on the latest version you should see that everything is a lot more colourful - although don't worry if you dislike that as I will add a "simple" theme to switch off the fanciness ;-)

"devel" contains the latest working development version of metawards, so its version number will always be "last_release+XXXX". "master" always contains the latest release, so its version number will always be "last_release". The last release was 0.11.2. I'm likely to make 0.12.0 either today or Monday.

**Comment by chryswoods** [comment]
I'm going to close this as I think it is now resolved. Please feel free to reopen if it is still a problem.
