### ISSUE TITLE
String literals raise ValueErrors when used in custom variables

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#74]
**Description:**
Using a string literal for a custom variable raises a ValueError. E.g.:

<pre>
Traceback (most recent call last):
  File "python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "python37\Scripts\metawards.exe\__main__.py", line 7, in <module>
  File "python37\lib\site-packages\metawards\app\run.py", line 892, in cli
    custom = VariableSet.read(args.user_variables)
  File "python37\lib\site-packages\metawards\_variableset.py", line 806, in read
    f"Corrupted file {filename}. Expected at least "
ValueError: Corrupted file defs\lockdown_states.txt. Expected at least two words for the 'variable value', but got .my_val = "test"</pre>

**To Reproduce:**
`defs\lockdown_states.txt`
<pre>.my_val = "test"</pre>

**Environment:**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: devel: 0.10.0-178-g6ecb43f

**Comment by chryswoods** [comment]
What’s the use case for text-based variables? Currently they have to be numeric values (or can be understood as numeric via safe_eval_float (https://github.com/metawards/MetaWards/blob/01d89dafdb881b5f4aeb7afcee4f8d16000a7c98/src/metawards/utils/_safe_eval_float.py#L7).

The logic of switching from horizontal to vertical files depends on numeric variables, so it would be a challenge to add support for text. For a good use case it may be worth it.

**Comment by chryswoods** [comment]
(should add - thanks for very clear and detailed issues - always very thought-provoking and with enough info that I can think about them even away from my laptop and on my phone)

**Comment by fentonscode** [comment]
My current use case is for datetime string literals. Having to split that into Y/M/D variables is a workaround which works. Currently I set a lock-down on a specific date, which synergises with a start date input parameter.

**Comment by fentonscode** [comment]
Would a prefix for types / or otherwise be useful? I've also found a minor problem where as they were all floats, something I needed as an int failed without a cast (was expecting it to be eval'd as an integer)

**Comment by chryswoods** [comment]
Yes, that's a good use case. I can quickly fix the double/int issue as I should change safe_eval_float to safe_eval_number. I will need to use some kind of prefix as at the moment "2020-12-31" would be interpreted as a float "2020 - 12 - 31" = 1977.0. Equally, "2020/12/31" would be 5.43.

I agree it will be useful - I've now also thought for the demographic code that it would be good to have strings that can say which demographic a population should move to. And the current parser is a bit kludgy as it evolved to deal with more use cases...

The fix will be in [fix-issue-74](https://github.com/metawards/MetaWards/tree/fix-issue-74), and I'll try to get at least a basic fix in place for 0.12.0.

**Comment by chryswoods** [comment]
In writing the code to support repeats I ended up also doing everything you wanted here :-)

Variables are now given their native types, or you can specify using the codes;

* s"this is a string"
* i"42"
* f"3.141"
* d"Monday July 3rd 2021"

but the code will figure out pretty much everything, so you should only need the type specifiers if you really want them.

You can specify dates using all of the formats supported by the [dateparser library](https://dateparser.readthedocs.io/en/latest/), although posix dates (2020-12-31) are much faster to read. You can still use evaluations, e.g. ".number = (3 + 7) * 10"

This now uses the Python csv library that will sniff out the right format and separator when parsing, and understands quoted strings (using ' or ").

You can write files in horizontal format, e.g. [horizontal.dat](https://github.com/metawards/MetaWards/blob/fix-issue-71/tests/data/horizontal.dat) or in vertical format for single variable sets, e.g. [vertical.dat](https://github.com/metawards/MetaWards/blob/fix-issue-71/tests/data/vertical.dat). There are other example input files in the [test data directory](https://github.com/metawards/MetaWards/tree/fix-issue-71/tests/data).

This is currently testing. I'll pull this into devel once the tests are complete. This will then automatically close this issue.
