### ISSUE TITLE
Multiple AttributeErrors on a Windows run

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#84]
**Describe the bug**
Multiple AttributeErrors thrown on runs on my Windows machine

**To Reproduce**
Steps listed in our previously running ensemble [here](https://github.com/UQ4covid/data/tree/master/metawards/initial_ensemble)

**Screenshots**
![uni1](https://user-images.githubusercontent.com/8965253/82473095-fbf8b400-9ac0-11ea-9bcb-9732a470b9f8.png)

**Environment:**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version metawards 0.12.0+21.gcfeef3b4

**Comment by fentonscode** [comment]
ETA: Previous exception

<pre>
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\site-packages\metawards\utils\_ru│
│n_models.py", line 340, in run_models                                                             │
│    337                         try:                                                              │
│    338                             result.wait()                                                 │
│    339                             output = result.get()                                         │
│  ❱ 340                             spinner.success()                                             │
│    341                         except Exception as e:                                            │
│    342                             spinner.failure()                                             │
│    343                             error = f"FAILED: {e.__class__} {e}"                          │
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\multiprocessing\pool.py", line   │
│657, in get                                                                                       │
│    654         if self._success:                                                                 │
│    655             return self._value                                                            │
│    656         else:                                                                             │
│  ❱ 657             raise self._value                                                             │
│    658                                                                                           │
│    659     def _set(self, i, obj):                                                               │
│    660         self._success, self._value = obj                                                  │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'NoneType' object has no attribute '_debugging_enabled'</pre>

**Comment by chryswoods** [comment]
Thanks - found and fixed the error. Just adding a unit test to stop this from happening again...

**Comment by chryswoods** [comment]
I believe this is fixed - the CI running now should give a better idea. Fix in the attached PR, which if accepted will close this issue.

**Comment by chryswoods** [comment]
fix-issue-85 fixes the problem for you, I believe, but my tests have exposed additional unicode errors on windows that I've not yet been able to solve. I am going to leave this now and fix it first thing tomorrow. Unicode issues are best not solved tired ;-)

**Comment by chryswoods** [comment]
Finally(!) I've got this working on windows. It was the result of me not being sufficiently careful to set the file encodings when opening and closing files. By default all files are now written using UTF-8 encoding (makes them portable and the same on all platforms). The code now detects errors when they happen and tries to re-encode text for the file or display if it is not UTF-8 (although everything should now be UTF-8). I've been working in a windows 10 VM in powershell and it all looks good - with the exception of that cursor movement character (?25h) that is from yaspin that you saw before. It is not ideal, but not a major problem to fix now. I will look at it again during a polish. CI now works, so I will merge the pull request which will close this issue.
