### ISSUE TITLE
Setup installer occasionally fails on _output_core byte-code file

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#86]
**Description**

Just a small note that sometimes I have to run the "make install" command twice recently as the `_output_core*.pyd` byte-code file appears to be left open and have a file handle associated with it. I do not know if this is part of the build process that is not releasing it, or if it is a holdover from previously running MetaWards. 

The stderr/console output is the classic `[WinError 5]`, running `make install` again clears it.

**Comment by chryswoods** [comment]
Thanks - the make install is just calling "pip install", which is using the standard setup.py install. All file handling is through there, so this would be an issue between setuptools and windows.

I don't have _output_core*.pyd files when I build on Mac or Linux, so I guess these are being created by visual studio? Cython converts the file.pyx straight into file.c, which is compiled directly. There are a small number of pxd files (e.g. src/metawards/utils/_rate_to_prob.pxd), which declare inline files or link to C libraries, but no pyd files.

Having googled, I see that pyd files are windows-specific things that act a little like shared link libraries. This is handled via Visual Studio, setuptools or the python interpreter, and so isn't related to MetaWards.

**Comment by chryswoods** [comment]
I'm going to close this as there isn't anything I can do. Re-open if the problem increases in frequency or appears to correlate with a specific commit to the code.
