### ISSUE TITLE
Version string output doesn't match official version

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#96]
**Description**
Running `metawards --version` produces `0.12.0 *` rather than `1.0.0 *`

**To Reproduce**
Clone from latest available (035e9ea), run `make` then `make install`, finally `metawards --version`. Output: `0.12.0+60.g035e9eac`

**Environment:**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: metawards 1.0.0

**Comment by lohedges** [comment]
HI @fentonscode, I see the correct output with a fresh install on Linux. Is it possible that you have multiple metwards packages installed in your Python environment, or have installed it into a different environment to the Python interpreter that you are using?

Could you try the following to find your path (having launched the Python interpreter.)

```python
import sys
print("\n".join(sys.path))
```

Then look in the `lib/python3.?/site-packages` directory for metawards packages, e.g. for me:

```sh
ls -ld /home/lester/.conda/envs/metawards/lib/python3.8/site-packages/meta* 
drwxr-sr-x 11 lester lester 4096 May 26 10:23 /home/lester/.conda/envs/metawards/lib/python3.8/site-packages/metawards
drwxr-sr-x  2 lester lester 4096 May 26 10:23 /home/lester/.conda/envs/metawards/lib/python3.8/site-packages/metawards-1.0.0.dist-info
```

This shows that I only have version 1.0 installed.

If multiple packages are installed in the same environment then it should load the one with the highest version number. However, if your path is searching multiple lib directories, then it will take the package that it finds first, i.e. directories earlier in the path take precedence.

If you just see one package, then I'll dust off my Windows box and try it out.

Cheers.

**Comment by fentonscode** [comment]
Hi @lohedges, I was able to install 1.0.0 correctly though `pip install --upgrade metawards` after a build, which suggests that the build system isn't making 1.0.0 at the moment for me. That explains my confusion, as prior to the official 1.0.0 I always installed from source

I only had a single metawards installation on the system which was building as:
 `0.12.0+60.g035e9eac`

**Comment by lohedges** [comment]
Thanks for the update. That's strange, both ways should work fine. I'll boot into Windows after lunch to see if I can reproduce.

**Comment by lohedges** [comment]
Ah, I think you might not have fetched the tags from the remote repository prior to building. Could you try:

```sh
git fetch --all --tags
```

You should see something like:

```
 * [new tag]           1.0.0      -> 1.0.0
```

Then try re-running the build and see if it works. I assume you only had tags up to version 0.12.0, hence the build using that rather than 1.0.0.

**Comment by fentonscode** [comment]
Fixed now, thanks @lohedges . I guess it's the recent changes in branches that's stopped `pull` getting all the tags?

**Comment by lohedges** [comment]
Great, glad it's now working. I'll close this now.

>  I guess it's the recent changes in branches that's stopped pull getting all the tags?

I'm not sure. It depends on your git setup and whether your working a direct clone of the main repository (as I am) or your own fork, where the main repository is an upstream remote. For example, the `--all` in the command above was needed to pull in tags from _all_ remotes, not just origin. I think the default behaviour regarding tags with pull/fetch has changed over time too, so you might see something different with old versions of git.
