### ISSUE TITLE
Custom extractors are not building

### ISSUE THREAD

**Issue by fentonscode** [metawards/MetaWards#97]
**Description**
A custom extractor, previously used with version 0.12.0 is now raising exceptions in 1.0.0. It appears there is a problem with the import system (possibly related #59, #80 and #82). This extractor was used to build an ensemble [here](https://github.com/UQ4covid/data/tree/master/metawards/initial_ensemble) 

<pre>
Traceback (most recent call last):
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\site-packages\metawards\utils\_im│
│port_module.py", line 20, in import_module                                                        │
│    17     try:                                                                                   │
│    18         import importlib                                                                   │
│    19         m = importlib.import_module(module)                                                │
│  ❱ 20     except SyntaxError as e:                                                               │
│    21         Console.error(                                                                     │
│    22             f"\nSyntax error when importing {module}\n"                                    │
│    23             f"{e.__class__.__name__}:{e}\n"                                                │
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 122,│
│in import_module                                                                                  │
│    119         if not package:                                                                   │
│    120             msg = ("the 'package' argument is required to perform a relative "            │
│    121                    "import for {!r}")                                                     │
│  ❱ 122             raise TypeError(msg.format(name))                                             │
│    123         for character in name:                                                            │
│    124             if character != '.':                                                          │
│    125                 break                                                                     │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: the 'package' argument is required to perform a relative import for '..\\..\\..\\uq4covid\\model_config\\metawards\\only_i_per_ward'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
┌──────────────────────────────────────────────────────────────────────────────────────────────────┐
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\runpy.py", line 193, in          │
│_run_module_as_main                                                                               │
│    190     if alter_argv:                                                                        │
│    191         sys.argv[0] = mod_spec.origin                                                     │
│    192     return _run_code(code, main_globals, None,                                            │
│  ❱ 193                      "__main__", mod_spec)                                                │
│    194                                                                                           │
│    195 def run_module(mod_name, init_globals=None,                                               │
│    196                run_name=None, alter_sys=False):                                           │
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code │
│     82                        __loader__ = loader,                                               │
│     83                        __package__ = pkg_name,                                            │
│     84                        __spec__ = mod_spec)                                               │
│  ❱  85     exec(code, run_globals)                                                               │
│     86     return run_globals                                                                    │
│     87                                                                                           │
│     88 def _run_module_code(code, init_globals=None,                                             │
│ File "C:\Users\cf502\AppData\Local\Programs\Python\Python37\Scripts\metawards.exe\__main__.py",  │
│line 7, in <module>                                                                               │
│ File                                                                                             │
│"c:\users\cf502\appdata\local\programs\python\python37\lib\site-packages\metawards\app\run.py",   │
│line 1103, in cli                                                                                 │
│    1100                             mixer=mixer,                                                 │
│    1101                             mover=mover,                                                 │
│    1102                             profiler=profiler,                                           │
│  ❱ 1103                             parallel_scheme=parallel_scheme)                             │
│    1104                                                                                          │
│    1105         if result is None or len(result) == 0:                                           │
│    1106             Console.print("No output - end of run")                                      │
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\site-packages\metawards\utils\_ru│
│n_models.py", line 464, in run_models                                                             │
│    461     else:                                                                                 │
│    462         from ..extractors._extract_custom import build_custom_extractor                   │
│    463         extractor = build_custom_extractor(extractor)                                     │
│  ❱ 464                                                                                           │
│    465     funcs = get_summary_functions(network=network, results=outputs,                       │
│    466                                   output_dir=output_dir, extractor=extractor,             │
│    467                                   nthreads=nthreads)                                      │
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\site-packages\metawards\extractor│
│s\_extract_custom.py", line 93, in build_custom_extractor                                         │
│     90         from ..utils._import_module import import_module                                  │
│     91                                                                                           │
│     92         module = import_module(func_module)                                               │
│  ❱  93                                                                                           │
│     94         if module is None:                                                                │
│     95             # we cannot find the extractor                                                │
│     96             Console.error(f"Cannot find the extractor '{custom_function}'."               │
│ File "c:\users\cf502\appdata\local\programs\python\python37\lib\site-packages\metawards\utils\_im│
│port_module.py", line 35, in import_module                                                        │
│    32     except Exception:                                                                      │
│    33         Console.error(                                                                     │
│    34             f"\nError when importing {module}\n"                                           │
│  ❱ 35             f"{e.__class__.__name__}:{e}\n")                                               │
│    36         m = None                                                                           │
│    37                                                                                            │
│    38     if m is None:                                                                          │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
UnboundLocalError: local variable 'e' referenced before assignment
</pre>

**Reproduction**
Extractor code [here](https://github.com/UQ4covid/uq4covid/blob/master/model_config/metawards/only_i_per_ward.py)
See metawards run script [here](https://github.com/UQ4covid/data/blob/master/metawards/initial_ensemble/runscript.bat)

**Environment:**
 - OS: Windows 10 x64
 - Python: 3.7.4
 - Version: metawards 1.0.0

**Comment by chryswoods** [comment]
I've just pushed a fix to "devel" (3ef18524b563e0a76e68f5dfc5b1ae8f338a5115). The issue was that the extractor was being imported from a different directory. I'll merge this in to a new release when I am back from holiday. Until then, you can either pull and build from devel or move the extractor into the same directory from which the code is run.

**Comment by fentonscode** [comment]
Thanks @chryswoods , I was hoping there'd be enough preamble to not bother you on holiday!

**Comment by chryswoods** [comment]
Closing as fixed is now merged into devel
